DROP DATABASE IF EXISTS Hangman;

CREATE DATABASE Hangman;

USE Hangman;

CREATE TABLE Game_TBL(
Game_ID INT NOT NULL AUTO_INCREMENT,
State ENUM ('created','started','finished'),
Word_State VARCHAR(255),
Guess_Count INT NOT NULL,
PRIMARY KEY (Game_ID),
CHECK (State IN ('created','started','finished'))  
);

CREATE TABLE Word_TBL(
Word_ID INT NOT NULL AUTO_INCREMENT,
Word VARCHAR(255) NOT NULL,
PRIMARY KEY (Word_ID)  
);

CREATE TABLE User_TBL(
User_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (User_ID)  
);

CREATE TABLE Player_TBL(
Player_ID INT NOT NULL AUTO_INCREMENT,
User_Name VARCHAR(255) UNIQUE NOT NULL,
User_ID INT NOT NULL,
Game_ID INT NOT NULL,
PRIMARY KEY (Player_ID),  
FOREIGN KEY (User_ID) REFERENCES User_TBL (User_ID),
FOREIGN KEY (Game_ID) REFERENCES Game_TBL (Game_ID)  
);

CREATE TABLE GameWord_TBL(
GameWord_ID INT NOT NULL AUTO_INCREMENT,
Game_ID INT NOT NULL,
Word_ID INT NOT NULL,
PRIMARY KEY (GameWord_ID),
FOREIGN KEY (Game_ID) REFERENCES Game_TBL (Game_ID),
FOREIGN KEY (Word_ID) REFERENCES Word_TBL (Word_ID)
);  