CREATE TABLE Liga(
Liga_ID INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,  
PRIMARY KEY (Liga_ID)
);
  
CREATE TABLE Fussballverein(
Fussballverein_ID INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
PRIMARY KEY (Fussballverein_ID)
FK_Liga INT NOT_NULL AUTO_INCREMENT,
FOREIGN KEY (FK_Liga) REFERENCES Liga (Liga_ID),
);
  
CREATE TABLE Mannschaft(
Mannschaft_ID INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,  
PRIMARY KEY (Mannschaft_ID)
);
  
CREATE TABLE Spieler(
Spieler_ID INT NOT_NULL AUTO_INCREMENT,
FK_Mannchaft INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,  
PRIMARY KEY (Spieler_ID),
FOREIGN KEY (FK_Mannschaft) REFERENCES Mannschaft (Mannschaft_ID)
);

CREATE TABLE Trikot(
Trikot_ID INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
Trikotnummer VARCHAR(2),
Farbe VARCHAR(30) NOT NULL,
PRIMARY KEY (Trikot_ID)
);
  
CREATE TABLE Trainer(
Trainer_ID INT NOT_NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,  
PRIMARY KEY (Trainer_ID)
);
  